import { readFile, readdir, writeFile } from "node:fs/promises";
import vm from "node:vm";

const ROOT = new URL("../", import.meta.url);
const OUTPUT = new URL("ARCHITECTURE.md", ROOT);
const checkOnly = process.argv.includes("--check");

async function lineCount(path) {
  const source = await readFile(new URL(path, ROOT), "utf8");
  return source.split(/\r?\n/).length;
}

const manifestSource = await readFile(new URL("src/module-manifest.js", ROOT), "utf8");
const context = { self: {} };
vm.runInNewContext(manifestSource, context, { filename: "src/module-manifest.js" });
const modules = context.self.PlaySputnikModules;

if (!Array.isArray(modules) || !modules.length) {
  throw new Error("Module manifest did not expose PlaySputnikModules");
}
const modulePaths = modules.map(({ path }) => path);
const moduleGlobals = modules.map(({ global }) => global).filter(Boolean);
if (new Set(modulePaths).size !== modulePaths.length) {
  throw new Error("Module manifest contains duplicate paths");
}
if (new Set(moduleGlobals).size !== moduleGlobals.length) {
  throw new Error("Module manifest contains duplicate globals");
}
const sourceModules = (await readdir(new URL("src/", ROOT)))
  .filter((name) => /^app-.*\.js$/.test(name))
  .map((name) => `src/${name}`)
  .sort();
const registeredSourceModules = modulePaths.filter((path) => /^src\/app-.*\.js$/.test(path)).sort();
if (JSON.stringify(sourceModules) !== JSON.stringify(registeredSourceModules)) {
  throw new Error("Every src/app-*.js file must appear exactly once in the module manifest");
}

const moduleRows = await Promise.all(modules.map(async ({ phase, path, global, role }) => (
  `| ${phase} | \`${path}\` | ${global ? `\`${global}\`` : "catalog side effect"} | ${await lineCount(path)} | ${role} |`
)));
const appLines = await lineCount("app.js");
const styleFiles = ["styles/foundation.css", "styles/components.css", "styles/polish.css", "styles/themes.css"];
const styleLines = await Promise.all(styleFiles.map(lineCount));
const cssLines = styleLines.reduce((sum, count) => sum + count, 0);
const htmlLines = await lineCount("index.html");

const output = `# PlaySputnik Architecture

Generated by \`node scripts/architecture-map.mjs\` from
\`src/module-manifest.js\`. Do not edit the generated module table manually.

## Start Here

- Product composition and DOM orchestration: \`app.js\` (${appLines} lines).
- Persisted profile contract: \`src/app-state-migrations.js\` then
  \`src/app-state.js\`.
- Module boot order and ownership: \`src/module-manifest.js\`.
- Product markup: \`index.html\` (${htmlLines} lines).
- Theme and component styles: \`styles/*.css\` (${cssLines} lines total);
  \`styles.css\` is the cached-shell compatibility entrypoint.
- Backend API boundary: \`backend/worker.mjs\`.
- Data refresh and validation: \`scripts/update-*.mjs\` and
  \`scripts/validate-data.mjs\`.
- Required verification: \`./scripts/check.sh\`.

## Change Routing

| Change | Read first |
| --- | --- |
| Taste scoring or recommendations | \`app-score.js\`, \`app-recommend.js\`, \`app-ranking.js\` |
| User library or saved profile | \`app-state-migrations.js\`, \`app-state.js\`, \`app-library.js\` |
| Search or external games | \`app-search.js\`, \`app-enrichment.js\`, \`backend/worker.mjs\` |
| Comparison or rate-later | \`app-decisions.js\` |
| Game detail behavior | \`app-detail.js\`, \`app-detail-view.js\`, then orchestration in \`app.js\` |
| Copy or localization | \`app-i18n.js\`, \`i18n-en.js\`, \`i18n-ru.js\` |
| Offline boot | \`module-manifest.js\`, \`index.html\`, \`sw.js\` |
| Data quality | \`data/*.json\`, \`validate-data.mjs\`, \`editorial-data-check.mjs\` |

## Runtime Modules

The order below is executable boot order and offline-cache order.

| Phase | Module | Global | Lines | Ownership |
| ---: | --- | --- | ---: | --- |
${moduleRows.join("\n")}

## Architectural Contracts

1. \`app.js\` composes modules and owns DOM event wiring; reusable domain logic
   belongs in \`src/app-*.js\`.
2. Persisted state changes require a migration and a
   \`state-migrations-test.mjs\` case.
3. New runtime modules are registered once in \`module-manifest.js\`; boot and
   Service Worker caching consume the same order.
4. Expensive per-game work must be memoized per render and invalidated at the
   top of \`render()\`.
5. Provider facts remain source-attributed; deterministic local output is the
   fallback when live providers are unavailable.
6. Invisible regression classes become gates in \`check.sh\` and CI.
`;

if (checkOnly) {
  const existing = await readFile(OUTPUT, "utf8").catch(() => "");
  if (existing !== output) {
    console.error("❌ ARCHITECTURE.md is stale; run node scripts/architecture-map.mjs");
    process.exit(1);
  }
  console.log(`✅ architecture map matches ${modules.length} runtime modules`);
} else {
  await writeFile(OUTPUT, output);
  console.log(`Updated ARCHITECTURE.md (${modules.length} runtime modules)`);
}
