(() => {
  const PLAYABLE_STATES = ["owned", "owned_forever", "subscription", "playing", "paused", "want_to_finish"];
  const runtimeApiOrigin = String(window.PlaySputnikRuntime?.apiOrigin || "").replace(/\/+$/, "");
  const localApiOrigin = `http://127.0.0.1:${window.__playsputnikSearchPort || 4191}`;
  const apiOrigin = runtimeApiOrigin || localApiOrigin;

  window.PlaySputnikConfig = {
    STORAGE_KEY: "playsputnik.prototype.state.v2",
    API_ORIGIN: apiOrigin,
    API_MODE: runtimeApiOrigin ? "production" : "local",
    PROVIDER_SEARCH_ENDPOINT: `${apiOrigin}/api/search`,
    APP_VIEWS: {
      today: {
        label: "Today",
        summary: "Tonight pick, first value proof, and the short plan.",
        cluster: "play",
        shelf: "smart",
      },
      library: {
        label: "Library",
        summary: "Owned, subscription, playing, paused, completed, and saved games in one queue.",
        cluster: "library",
        shelf: "library",
      },
      discover: {
        label: "Discover",
        summary: "Search, broad catalog covers, taste radar, and subscription drops without turning the app into a price tracker.",
        cluster: "play",
        shelf: "catalog",
      },
      wishlist: {
        label: "Wishlist",
        summary: "Wishlist, deal candidates, buy guardrails, and games worth watching.",
        cluster: "buy",
        shelf: "wishlist",
      },
      taste: {
        label: "Taste",
        summary: "What the companion knows, what it learned recently, and how confident it should be.",
        cluster: "play",
        shelf: "smart",
      },
      deals: {
        label: "Deals",
        summary: "Live PS Store discounts sorted by value. Filtered to your region and taste.",
        cluster: "buy",
        shelf: "catalog",
      },
      data: {
        label: "Data",
        summary: "Source health, refresh rules, catalog backbone, and prototype diagnostics.",
        cluster: "play",
        shelf: "catalog",
      },
      stats: {
        label: "Stats",
        summary: "Your library by status, top taste atoms, total HLTB hours, and catalog coverage.",
        cluster: "library",
        shelf: "library",
      },
    },
    LIBRARY_QUEUE_FILTERS: {
      all: { label: "All", summary: "Everything remembered, playable, saved, or suggested." },
      active: { label: "Active", summary: "Currently playing, paused, finish-later, and play-later items." },
      access: { label: "Access", summary: "Owned, permanent, or subscription games that can replace a purchase." },
      wishlist: { label: "Wishlist", summary: "Saved or desired games that still need a decision." },
      finished: { label: "Done", summary: "Completed, dropped, hidden, or otherwise closed items." },
    },
    WISHLIST_QUEUE_FILTERS: {
      all: { label: "All", summary: "Every watched game with a purchase or wait decision." },
      buy: { label: "Buy", summary: "Confident buy-zone items inside current guardrails." },
      wait: { label: "Wait", summary: "Good games where price, risk, or timing says hold." },
      verify: { label: "Verify", summary: "Price signals that need source confirmation." },
      missing: { label: "Missing", summary: "Wishlist intent without a usable price yet." },
    },
    USER_STATE_LABELS: {
      later: "Play later",
      saved: "Saved",
      want_to_finish: "Want to finish",
      paused: "Paused",
      owned: "Owned",
      owned_forever: "Owned forever",
      subscription: "Subscription",
      playing: "Playing",
      completed: "Completed",
      dropped: "Dropped",
      hidden: "Hidden",
    },
    PLAYABLE_STATES,
    ACCESS_STATES: ["owned", "owned_forever", "subscription"],
    COMPLETION_STATUS_STATES: ["playing", "paused", "want_to_finish", "completed", "dropped"],
    LIBRARY_ACTIVE_STATES: ["saved", ...PLAYABLE_STATES],
    RANK_EXCLUDED_STATES: ["hidden", "completed", "dropped"],
    MEMORY_STATE_GROUPS: [
      {
        label: "Play",
        actions: [
          ["playing", "Playing"],
          ["paused", "Pause"],
          ["want_to_finish", "Finish"],
        ],
      },
      {
        label: "Access",
        actions: [
          ["saved", "Wishlist"],
          ["owned", "Owned"],
          ["owned_forever", "Forever"],
          ["subscription", "Plus"],
        ],
      },
      {
        label: "Outcome",
        actions: [
          ["completed", "Done"],
          ["dropped", "Drop"],
          ["hidden", "No"],
          ["", "Clear"],
        ],
      },
    ],
    QUICK_REACTION_LABELS: {
      loved: "Liked",
      not_for_me: "Marked not for me",
      unplayed: "Marked not played",
      clear: "Cleared",
    },
    QUICK_TASTE_FIRST_TARGET: 5,
    QUICK_TASTE_USABLE_TARGET: 8,
    QUICK_TASTE_SHARP_TARGET: 10,
    TITLE_ENRICHMENT_RULES: [
      {
        terms: ["stray"],
        atoms: ["exploration", "cozy", "short", "story", "indie"],
        summary: "Small atmospheric adventure with light puzzle/exploration pull.",
        risk: "Could feel too slight if the player wants combat depth or a long arc.",
        session: "short",
      },
      {
        terms: ["grand theft auto", "gta"],
        atoms: ["open-world", "crime", "action", "sandbox", "long"],
        summary: "Large crime sandbox with high freedom, spectacle, and long-session pull.",
        risk: "Can be too sprawling when the player wants a focused story evening.",
        session: "long",
      },
      {
        terms: ["outer worlds"],
        atoms: ["rpg", "choice", "funny", "sci-fi", "systems"],
        summary: "Satirical sci-fi RPG candidate with choice and companion/build appeal.",
        risk: "May underwhelm if the player wants a huge cinematic blockbuster rather than a systems RPG.",
        session: "long",
      },
      {
        terms: ["kingdom come", "kcd"],
        atoms: ["rpg", "realistic", "story", "systems", "long"],
        summary: "Historical RPG candidate where immersion, realism, and slow-burn systems matter.",
        risk: "Can be friction-heavy if the player wants fast cinematic progress rather than simulation texture.",
        session: "long",
      },
      {
        terms: ["hellblade", "senua"],
        atoms: ["story", "cinematic", "psychological", "short", "dark"],
        summary: "Short cinematic psychological story candidate with strong atmosphere.",
        risk: "Intensity and narrow interactivity need a mood check before a confident recommendation.",
        session: "short",
      },
      {
        terms: ["007", "bond"],
        atoms: ["cinematic", "stealth", "action", "story"],
        summary: "Cinematic spy-action candidate with stealth and set-piece appeal.",
        risk: "Needs real metadata before claiming mission structure, platforms, or launch details.",
        session: "medium",
      },
      {
        terms: ["wukong", "black myth", "nightreign", "elden ring"],
        atoms: ["action", "challenge", "mythic", "soulslike"],
        summary: "High-skill action candidate where combat feel and difficulty tolerance matter.",
        risk: "Could be a poor weeknight fit if the player wants low-friction story progress.",
        session: "medium",
      },
      {
        terms: ["silksong", "hollow knight", "prince of persia", "lost crown"],
        atoms: ["challenge", "metroidvania", "exploration", "platforming"],
        summary: "Exploration-heavy action/platforming candidate with mastery and map-reading pull.",
        risk: "Backtracking or difficulty can be friction if the player wants cinematic flow.",
        session: "medium",
      },
      {
        terms: ["civilization", "civ ", "civ7", "civ 7"],
        atoms: ["strategy", "turn-based", "systems", "long"],
        summary: "Long strategy candidate where planning depth matters more than story momentum.",
        risk: "Can eat a whole evening and is rarely a quick campaign-style recommendation.",
        session: "long",
      },
      {
        terms: ["balatro"],
        atoms: ["roguelike", "systems", "short", "indie"],
        summary: "Short-session systems candidate built around repeatable runs and optimization.",
        risk: "Almost no story pull, so it needs appetite for pure mechanics.",
        session: "short",
      },
      {
        terms: ["animal well", "blue prince"],
        atoms: ["puzzle", "exploration", "strange", "indie"],
        summary: "Quiet puzzle/discovery candidate with strong curiosity value.",
        risk: "Can feel opaque if the player wants clear objectives or authored drama.",
        session: "short",
      },
      {
        terms: ["helldivers", "marathon", "arc raiders"],
        atoms: ["shooter", "multiplayer", "service", "co-op"],
        summary: "Social shooter candidate that may work as repeatable evening play.",
        risk: "Service structure and multiplayer dependence are the main personal-fit risks.",
        session: "short",
      },
      {
        terms: ["ready or not", "swat"],
        atoms: ["shooter", "tactical", "realistic", "co-op"],
        summary: "Tactical shooter candidate focused on realism and coordinated play.",
        risk: "Likely too procedural or tense for players seeking authored story momentum.",
        session: "medium",
      },
      {
        terms: ["metaphor", "final fantasy", "dragon age"],
        atoms: ["rpg", "story", "choice", "long"],
        summary: "Long story-RPG candidate where world, party, and systems commitment matter.",
        risk: "Needs a real appetite for long sessions, menus, and genre conventions.",
        session: "long",
      },
      {
        terms: ["astro bot"],
        atoms: ["platforming", "short", "playful", "cozy"],
        summary: "Compact, readable play-session candidate with low setup burden.",
        risk: "May feel lightweight if the player is chasing a major dramatic arc.",
        session: "short",
      },
      {
        terms: ["little nightmares"],
        atoms: ["horror", "puzzle", "tension", "short"],
        summary: "Compact horror/puzzle candidate with strong atmosphere and low time burden.",
        risk: "Pressure and grotesque tone may be the main personal-fit risk.",
        session: "short",
      },
      {
        terms: ["wolverine", "spider man", "spider-man"],
        atoms: ["action", "cinematic", "story", "superhero"],
        summary: "Prestige superhero action candidate for players who like authored spectacle.",
        risk: "May lean more combat-forward than story-first players expect.",
        session: "medium",
      },
      {
        terms: ["hades"],
        atoms: ["action", "roguelike", "systems", "short", "mythic"],
        summary: "Short-run action with systems depth and repeatable sessions.",
        risk: "Run repetition can frustrate players who prefer one-and-done campaigns.",
        session: "short",
      },
      {
        terms: ["baldur", "expedition 33", "clair obscur", "fable"],
        atoms: ["rpg", "choice", "systems", "story", "long"],
        summary: "RPG-shaped candidate where choice, builds, and commitment matter.",
        risk: "The time cost or combat format needs a taste check before strong ranking advice.",
        session: "long",
      },
      {
        terms: ["silent hill", "od", "horror"],
        atoms: ["horror", "story", "tension", "strange"],
        summary: "Atmospheric tension candidate for horror-tolerant story players.",
        risk: "Personal tolerance for pressure and scares is the main uncertainty.",
        session: "medium",
      },
      {
        terms: ["intergalactic", "judas", "control", "sci fi", "sci-fi"],
        atoms: ["sci-fi", "story", "action", "strange"],
        summary: "Strange sci-fi action/story candidate with strong taste-signal value.",
        risk: "Needs provider metadata before judging length, platform scope, or launch certainty.",
        session: "medium",
      },
    ],
    // Sputnik scale: 1–5 sputniks stored as 20–100 internally
    RATING_ACTIONS: [
      [100, "5"],
      [80, "4"],
      [60, "3"],
      [40, "2"],
      [20, "1"],
      ["", "Clear"],
    ],
  };
})();
